---
version: '3.8'

services:
  ws:
    container_name: 'filedrop-ws'
    build:
      context: ./filedrop-ws
      dockerfile: Dockerfile
    environment:
      - WS_HOST=0.0.0.0
      - WS_BEHIND_PROXY=yes
      - TURN_MODE=hmac
      - TURN_SERVER=turn:${HOST}
      - TURN_USERNAME=filedrop
      - TURN_SECRET=${TURN_SECRET}
    restart: unless-stopped

  web:
    container_name: 'filedrop-web'
    build:
      context: ./filedrop-web
      dockerfile: Dockerfile
      args:
        - REACT_APP_TITLE=${TITLE}
        - REACT_APP_SERVER=ws://${HOST}:${PORT}/ws/
        - REACT_APP_USE_BROWSER_ROUTER=1
    restart: unless-stopped

  coturn:
    container_name: 'filedrop-coturn'
    image: ghcr.io/coturn/coturn:edge-alpine
    command: --use-auth-secret --static-auth-secret=${TURN_SECRET} --no-tls --no-dtls
    network_mode: host
    restart: unless-stopped

  nginx:
    container_name: 'filedrop-nginx'
    image: nginx:alpine
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "${PORT}:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./conf/nginx:/config/nginx/
      - /docker-data/certbot/letsencrypt:/etc/letsencrypt
    command: /bin/sh -c "envsubst '$${DOMAIN}' < /config/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
